package com.tms.dto.request.ClFreshGetLead;

import com.fasterxml.jackson.annotation.JsonInclude;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SetLeadFresh {
    private Integer leadId;
    private Integer cpId;
    private Integer callinglistId;
    private Integer agcId;
    private String agcCode;
    private Integer orgId;
    private String ccCode;
    private String name;
    private String phone;
    private Integer prodId;
    private String prodName;
    private Integer assigned;
    private Integer calledBy;
    private String address;
    private String province;
    private String district;
    private String subdistrict;
    private String comment;
    private Integer lastCallStatus;
    private Integer dayCall;
    private Integer totalCall;
    private String amount;
    private Integer leadStatus;
    private Integer result;
    private String userDefin01;
    private String userDefin02;
    private String userDefin03;
    private String userDefin04;
    private String userDefin05;
    private String createDate;
    private String modifyDate;
    private Integer modifyBy;
    private String leadType;
    private String agcLeadAddress;
    private String otherName1;
    private String otherPhone1;
    private String otherName2;
    private String otherPhone2;
    private String otherName3;
    private String otherPhone3;
    private String otherName4;
    private String otherPhone4;
    private String otherName5;
    private String otherPhone5;
    private String lastCallTime;
    private String nextCallTime;
    private Integer numberOfDay;
    private Integer attemptBusy;
    private Integer attemptNoans;
    private Integer attemptUnreachable;
    private Integer attemptOther1;
    private Integer attemptOther2;
    private Integer attemptOther3;
    private String clickId;
    private String affiliateId;
    private String subid1;
    private String subid2;
    private String subid3;
    private String subid4;
    private String subid5;
    private String networkid;
    private String pid;
    private String trackingUrlId;
    private String offerId;
    private String agcOfferId;
    private String terms;
    private String price;
    private String unit;
    private Integer customerAge;
    private String customerEmail;
    private String customerComment;
    private String internalComment;
    private String carrierComment;
    private Integer groupId;
    private String neighborhood;
    private String postalCode;
    private Integer trackerId;
    private String agentNote;
    private String firstCallTime;
    private Integer firstCallBy;
    private Integer firstCallStatus;
    private String firstCallReason;
    private String firstCallComment;
    private String fcrTime;
    private Integer fcrBy;
    private Integer fcrStatus;
    private String fcrReason;
    private String fcrComment;
    private Integer crmActionType;
    private Integer team;
    private Integer teamSupervisor;
    private Integer agentHold;
    private String appointmentDate;
    private String deliveryPackageCode;
}
