server:
  port: 8082

spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none

config:
  org-id: 4
  is-run-db-log: true